### ISSUE TITLE
Refactor: use `scope` for more smarter removing

### ISSUE THREAD

**Issue by imcuttle** [imcuttle/babel-plugin-danger-remove-unused-import#4]
#3

**Comment by ndelangen** [comment]
The PR referenced is merged, is this done?

**Comment by imcuttle** [comment]
@ndelangen  It's a plan to do it.

**Comment by imcuttle** [comment]
@ndelangen   Hi, babel-plugin-danger-remove-unused-import@2  using scope for finding unused reference.
